In [66]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Introduction to tensors

In [67]:
scalar = torch.tensor(8)
scalar

tensor(8)

In [68]:
scalar.ndim
scalar.item()

8

In [69]:
vector = torch.tensor ([7,7])
vector.ndim
vector.shape

torch.Size([2])

In [70]:
###creating matrix
matrix = torch.tensor([[7,8],[9,0]])
matrix.ndim


2

In [71]:
matrix[0]

tensor([7, 8])

In [72]:
matrix[1]

tensor([9, 0])

In [73]:
matrix.shape

torch.Size([2, 2])

In [74]:
####Tensors
tensor = torch.tensor([[[7,8,7], [1,2,3], [4,5,6]]])
tensor

tensor([[[7, 8, 7],
         [1, 2, 3],
         [4, 5, 6]]])

In [75]:
tensor.shape

torch.Size([1, 3, 3])

In [76]:
tensor[0]

tensor([[7, 8, 7],
        [1, 2, 3],
        [4, 5, 6]])

In [77]:
tensor[0,1,1]

tensor(2)

In [78]:
tensor[0,2,1]

tensor(5)

In [79]:
tensor[0,0,1]

tensor(8)

In [80]:
tensor[0,2,2]

tensor(6)

In [81]:
###Random tensors
random_tensor = torch.rand(3,4,3)

In [82]:
random_tensor.shape

torch.Size([3, 4, 3])

In [83]:
random_tensor.ndim

3

In [84]:
random_tensor

tensor([[[0.9904, 0.8168, 0.9700],
         [0.8840, 0.9580, 0.5323],
         [0.5515, 0.9258, 0.8616],
         [0.3786, 0.2881, 0.8390]],

        [[0.7760, 0.0369, 0.1463],
         [0.7660, 0.3836, 0.7308],
         [0.0356, 0.2544, 0.3249],
         [0.5802, 0.7149, 0.4671]],

        [[0.0237, 0.8444, 0.6934],
         [0.8526, 0.4065, 0.8438],
         [0.1916, 0.4846, 0.7119],
         [0.1671, 0.6080, 0.9550]]])

In [85]:
##Creating something similar to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [86]:
torch_random = torch.rand(size=(3,2,3))

In [87]:
torch_random

tensor([[[0.2774, 0.1441, 0.1475],
         [0.8005, 0.0285, 0.2627]],

        [[0.5755, 0.2412, 0.0417],
         [0.8567, 0.0777, 0.4072]],

        [[0.8619, 0.4475, 0.8653],
         [0.1276, 0.2232, 0.0085]]])

In [88]:
torch_random = torch.rand(size=(4,4,3))

In [89]:
torch_random

tensor([[[0.3106, 0.9629, 0.0099],
         [0.4701, 0.4260, 0.2648],
         [0.6099, 0.2539, 0.1904],
         [0.7560, 0.5310, 0.4455]],

        [[0.8313, 0.5446, 0.7774],
         [0.8384, 0.2506, 0.0700],
         [0.7953, 0.1338, 0.0425],
         [0.3520, 0.9263, 0.8836]],

        [[0.2712, 0.9948, 0.7710],
         [0.2191, 0.3039, 0.7595],
         [0.3610, 0.7610, 0.1561],
         [0.3958, 0.7480, 0.5067]],

        [[0.7603, 0.4370, 0.2122],
         [0.0259, 0.4002, 0.8844],
         [0.0596, 0.0671, 0.5652],
         [0.2169, 0.6142, 0.2417]]])

In [90]:
torch_random[1,3,2]

tensor(0.8836)

In [91]:
torch_random[3,0,1]

tensor(0.4370)

In [92]:
#Creating tensors with 0's and 1's
zeroes = torch.zeros(size=(4,5))
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

creating a range of tensors and tensors-like

In [93]:
 range1 = torch.arange(start=1, end=12, step=2)
 range1

tensor([ 1,  3,  5,  7,  9, 11])

In [94]:
range1zeros = torch.zeros_like(range1)
range1zeros

tensor([0, 0, 0, 0, 0, 0])

In [98]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16,
                               device = 'cpu',
                               requires_grad = False)

In [105]:
float2int_tensor = float_32_tensor.type(torch.int32)

In [99]:
###Directly convert the float_32_tensor to float_16_tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [103]:
###Tensors of type integer

int_tensor = torch.tensor([3, 5, 9], dtype = torch.uint32,
                          device = 'cpu',
                          requires_grad = False)

In [104]:
int2float_tensor = int_tensor.type(torch.float32)

Get some tensor details

In [106]:
print(int2float_tensor)

tensor([3., 5., 9.])


In [107]:
print(f"tensor datatype: {int2float_tensor.dtype}")

tensor datatype: torch.float32


In [109]:
print(f"tensor shape: {int2float_tensor.shape}")

tensor shape: torch.Size([3])


In [110]:
print(f"Device on which the tensor is running: {int2float_tensor.device}")

Device on which the tensor is running: cpu


Manipulation of tensors

In [112]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [119]:
##Matrix multiplication
#Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [123]:
##Matrix multiplication(dot product)
print (f"1*1 + 2*2 + 3*3")
print (f"Equals: {1*1 + 2*2 + 3*3}")

1*1 + 2*2 + 3*3
Equals: 14


In [124]:
value = 0
for i in range(len(tensor)):
    value = value + (tensor[i]*tensor[i])
print(value)

tensor(14)


In [125]:
torch.matmul(tensor,tensor)

tensor(14)

one of the most common errors in deep learning are the shape errors

In [139]:
#Shapes for matrix multiplication
tensor1 = torch.tensor([[1,2],[3,4],[5,6]])
tensor1.shape


torch.Size([3, 2])

In [148]:
tensor2 = torch.tensor([[7,8],[9,10],[11,12]])
tensor2.shape

torch.Size([3, 2])

In [149]:
tensor3 = torch.tensor([[7,8,9],[8,9,0]])
tensor3.shape

torch.Size([2, 3])

In [150]:
result_tensor = torch.matmul(tensor1,tensor3)
print(result_tensor)

tensor([[23, 26,  9],
        [53, 60, 27],
        [83, 94, 45]])


In [151]:
result_tensor.shape

torch.Size([3, 3])

In [157]:
tensor4 = torch.tensor([[7],[8]])
tensor4.shape

torch.Size([2, 1])

In [160]:
result_tensor1 = torch.matmul(tensor1 , tensor4)
print(result_tensor1)

tensor([[23],
        [53],
        [83]])


#Adjusting tensor shape using transpose

In [161]:
tensor2.T, tensor2

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [162]:
tensor2.T.shape, tensor2.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [164]:
result_tensor2 = torch.matmul(tensor2.T,tensor2)

In [165]:
result_tensor2.shape

torch.Size([2, 2])