In [116]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Introduction to tensors

In [117]:
scalar = torch.tensor(8)
scalar

tensor(8)

In [118]:
scalar.ndim
scalar.item()

8

In [119]:
vector = torch.tensor ([7,7])
vector.ndim
vector.shape

torch.Size([2])

In [120]:
###creating matrix
matrix = torch.tensor([[7,8],[9,0]])
matrix.ndim


2

In [121]:
matrix[0]

tensor([7, 8])

In [122]:
matrix[1]

tensor([9, 0])

In [123]:
matrix.shape

torch.Size([2, 2])

In [124]:
####Tensors
tensor = torch.tensor([[[7,8,7], [1,2,3], [4,5,6]]])
tensor

tensor([[[7, 8, 7],
         [1, 2, 3],
         [4, 5, 6]]])

In [125]:
tensor.shape

torch.Size([1, 3, 3])

In [126]:
tensor[0]

tensor([[7, 8, 7],
        [1, 2, 3],
        [4, 5, 6]])

In [127]:
tensor[0,1,1]

tensor(2)

In [128]:
tensor[0,2,1]

tensor(5)

In [129]:
tensor[0,0,1]

tensor(8)

In [130]:
tensor[0,2,2]

tensor(6)

In [131]:
###Random tensors
random_tensor = torch.rand(3,4,3)

In [132]:
random_tensor.shape

torch.Size([3, 4, 3])

In [133]:
random_tensor.ndim

3

In [134]:
random_tensor

tensor([[[0.4319, 0.0130, 0.5872],
         [0.8867, 0.2231, 0.4883],
         [0.7719, 0.5956, 0.8597],
         [0.3956, 0.7258, 0.8361]],

        [[0.0154, 0.9166, 0.8023],
         [0.5943, 0.2825, 0.2075],
         [0.4735, 0.7807, 0.3653],
         [0.4575, 0.6798, 0.9965]],

        [[0.4331, 0.9427, 0.4362],
         [0.6885, 0.4348, 0.6679],
         [0.2432, 0.1535, 0.7381],
         [0.0203, 0.1211, 0.4766]]])

In [135]:
##Creating something similar to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [136]:
torch_random = torch.rand(size=(3,2,3))

In [137]:
torch_random

tensor([[[0.9266, 0.6748, 0.1716],
         [0.3213, 0.2470, 0.1586]],

        [[0.3809, 0.1767, 0.4607],
         [0.0668, 0.4501, 0.6325]],

        [[0.4239, 0.0170, 0.1027],
         [0.0451, 0.4909, 0.6750]]])

In [138]:
torch_random = torch.rand(size=(4,4,3))

In [139]:
torch_random

tensor([[[0.9459, 0.0996, 0.8372],
         [0.6396, 0.8584, 0.9826],
         [0.1827, 0.3083, 0.5557],
         [0.3955, 0.2694, 0.1118]],

        [[0.7471, 0.7842, 0.1016],
         [0.5571, 0.2571, 0.5116],
         [0.9575, 0.2710, 0.5507],
         [0.6568, 0.7311, 0.5061]],

        [[0.7197, 0.3646, 0.5307],
         [0.5703, 0.1251, 0.3493],
         [0.7734, 0.1977, 0.1662],
         [0.2023, 0.2603, 0.6611]],

        [[0.2530, 0.6531, 0.4381],
         [0.5288, 0.3392, 0.2662],
         [0.1930, 0.0137, 0.2541],
         [0.9701, 0.0665, 0.5031]]])

In [140]:
torch_random[1,3,2]

tensor(0.5061)

In [141]:
torch_random[3,0,1]

tensor(0.6531)

In [142]:
#Creating tensors with 0's and 1's
zeroes = torch.zeros(size=(4,5))
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

creating a range of tensors and tensors-like

In [143]:
 range1 = torch.arange(start=1, end=12, step=2)
 range1

tensor([ 1,  3,  5,  7,  9, 11])

In [144]:
range1zeros = torch.zeros_like(range1)
range1zeros

tensor([0, 0, 0, 0, 0, 0])

In [145]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16,
                               device = 'cpu',
                               requires_grad = False)

In [146]:
float2int_tensor = float_32_tensor.type(torch.int32)

In [147]:
###Directly convert the float_32_tensor to float_16_tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [148]:
###Tensors of type integer

int_tensor = torch.tensor([3, 5, 9], dtype = torch.uint32,
                          device = 'cpu',
                          requires_grad = False)

In [149]:
int2float_tensor = int_tensor.type(torch.float32)

Get some tensor details

In [150]:
print(int2float_tensor)

tensor([3., 5., 9.])


In [151]:
print(f"tensor datatype: {int2float_tensor.dtype}")

tensor datatype: torch.float32


In [152]:
print(f"tensor shape: {int2float_tensor.shape}")

tensor shape: torch.Size([3])


In [153]:
print(f"Device on which the tensor is running: {int2float_tensor.device}")

Device on which the tensor is running: cpu


Manipulation of tensors

In [154]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [155]:
##Matrix multiplication
#Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [156]:
##Matrix multiplication(dot product)
print (f"1*1 + 2*2 + 3*3")
print (f"Equals: {1*1 + 2*2 + 3*3}")

1*1 + 2*2 + 3*3
Equals: 14


In [157]:
value = 0
for i in range(len(tensor)):
    value = value + (tensor[i]*tensor[i])
print(value)

tensor(14)


In [158]:
torch.matmul(tensor,tensor)

tensor(14)

one of the most common errors in deep learning are the shape errors

In [159]:
#Shapes for matrix multiplication
tensor1 = torch.tensor([[1,2],[3,4],[5,6]])
tensor1.shape


torch.Size([3, 2])

In [160]:
tensor2 = torch.tensor([[7,8],[9,10],[11,12]])
tensor2.shape

torch.Size([3, 2])

In [161]:
tensor3 = torch.tensor([[7,8,9],[8,9,0]])
tensor3.shape

torch.Size([2, 3])

In [162]:
result_tensor = torch.matmul(tensor1,tensor3)
print(result_tensor)

tensor([[23, 26,  9],
        [53, 60, 27],
        [83, 94, 45]])


In [163]:
result_tensor.shape

torch.Size([3, 3])

In [164]:
tensor4 = torch.tensor([[7],[8]])
tensor4.shape

torch.Size([2, 1])

In [165]:
result_tensor1 = torch.matmul(tensor1 , tensor4)
print(result_tensor1)

tensor([[23],
        [53],
        [83]])


#Adjusting tensor shape using transpose

In [166]:
tensor2.T, tensor2

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [167]:
tensor2.T.shape, tensor2.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [168]:
result_tensor2 = torch.matmul(tensor2.T,tensor2)

In [169]:
result_tensor2.shape

torch.Size([2, 2])

Reshaping, stacking and squeezing  tensors

In [170]:
x1 = torch.arange(1,10)
x1, x1.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [171]:
x2 = torch.arange(2,10, step =2)
x2, x2.shape

(tensor([2, 4, 6, 8]), torch.Size([4]))

In [172]:
x1.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [173]:
x1.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [174]:
x1.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [175]:
x1.reshape(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

Reshaping the tensor x2


In [176]:
x2.reshape(2,2)

tensor([[2, 4],
        [6, 8]])

In [177]:
x2.reshape(1,2,2)

tensor([[[2, 4],
         [6, 8]]])

In [178]:
x2.reshape(1,4)

tensor([[2, 4, 6, 8]])

In [179]:
x2.reshape(4,1)

tensor([[2],
        [4],
        [6],
        [8]])

In [180]:
x2.reshape(1,1,4)

tensor([[[2, 4, 6, 8]]])

In [181]:
x2.reshape(1,4,1)

tensor([[[2],
         [4],
         [6],
         [8]]])

In [182]:
x2.reshape(2,1,2)

tensor([[[2, 4]],

        [[6, 8]]])

 If we want 2 rows; but pytorch has to figure out the number of columns automatically

In [183]:
x2.reshape(2,-1)

tensor([[2, 4],
        [6, 8]])

 If we want 2 columns; but pytorch has to figure out the number of columns automatically

In [184]:
x2.reshape(-1,2)

tensor([[2, 4],
        [6, 8]])

In [185]:
###Changing view of tensor
z= x1.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [186]:
#changing x changes z
z[:,0] = 5
z,x1

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [187]:
z[:,1:9] = 6
z,x1

(tensor([[5, 6, 6, 6, 6, 6, 6, 6, 6]]), tensor([5, 6, 6, 6, 6, 6, 6, 6, 6]))

In [188]:
##Stacking tensors on top of each other
x1_stacked = torch.stack([x,x,x,x],dim=1)
x1_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [189]:
x2_stacked = torch.stack([x2,x2,x2,x2],dim=0)
x2_stacked

tensor([[2, 4, 6, 8],
        [2, 4, 6, 8],
        [2, 4, 6, 8],
        [2, 4, 6, 8]])

In [190]:
x2_stacked = torch.stack([x2,x2,x2,x2],dim=1)
x2_stacked

tensor([[2, 2, 2, 2],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [8, 8, 8, 8]])

Now let us stack stack tensors with dim = 3

In [196]:
##reshape the tensor
x2_reshaped1 = torch.reshape(x2,(2,2))
x2_reshaped1

tensor([[2, 4],
        [6, 8]])

In [197]:
x2_reshaped2 = torch.reshape(x2,(1,2,2))
x2_reshaped2

tensor([[[2, 4]],

        [[6, 8]]])

In [199]:
x2_reshaped3 = torch.reshape(x2,(1,4))
x2_reshaped3

tensor([[2, 4, 6, 8]])

In [212]:
x2_stacked1dim0 = torch.stack([x2_reshaped1, x2_reshaped1, x2_reshaped1, x2_reshaped1 ],dim=0)
x2_stacked1dim0

tensor([[[2, 4],
         [6, 8]],

        [[2, 4],
         [6, 8]],

        [[2, 4],
         [6, 8]],

        [[2, 4],
         [6, 8]]])

In [213]:
x2_stacked1dim1 = torch.stack([x2_reshaped1, x2_reshaped1, x2_reshaped1, x2_reshaped1 ],dim=1)
x2_stacked1dim1

tensor([[[2, 4],
         [2, 4],
         [2, 4],
         [2, 4]],

        [[6, 8],
         [6, 8],
         [6, 8],
         [6, 8]]])

In [207]:
x2_stacked2 = torch.stack([x2_reshaped2, x2_reshaped2, x2_reshaped2, x2_reshaped2 ],dim=3)
x2_stacked2

tensor([[[[2, 2, 2, 2],
          [4, 4, 4, 4]]],


        [[[6, 6, 6, 6],
          [8, 8, 8, 8]]]])

In [208]:
print(f"original Tensor: {x2}")
print(f"reshaped Tensor1: {x2_reshaped1}")
print(f"reshaped Tensor2: {x2_reshaped2}")
print(f"stacked tensor with reshaped Tensor2: {x2_stacked}")
print(f"reshaped Tensor3: {x2_reshaped3}")

original Tensor: tensor([2, 4, 6, 8])
reshaped Tensor1: tensor([[2, 4],
        [6, 8]])
reshaped Tensor2: tensor([[[2, 4]],

        [[6, 8]]])
stacked tensor with reshaped Tensor2: tensor([[[[2, 2, 2, 2],
          [4, 4, 4, 4]]],


        [[[6, 6, 6, 6],
          [8, 8, 8, 8]]]])
reshaped Tensor3: tensor([[2, 4, 6, 8]])


Squeezing and unsqueezing tensors

In [214]:
x2_reshaped1

tensor([[2, 4],
        [6, 8]])

In [215]:
x2_reshaped1.shape

torch.Size([2, 2])

In [228]:
x2_reshaped_again1 = torch.reshape(x2_reshaped1,(1,4))
x2_reshaped_again1

tensor([[2, 4, 6, 8]])

In [231]:
x2_reshaped_again2 = torch.reshape(x2_reshaped2,(4,1))
x2_reshaped_again2

tensor([[2],
        [4],
        [6],
        [8]])

In [235]:
x2squeezed1 = x2_reshaped_again1.squeeze()
x2squeezed1.shape

torch.Size([4])

In [236]:
x2squeezed2 = x2_reshaped_again2.squeeze()
x2squeezed2.shape

torch.Size([4])