In [18]:
import torch
import pandas as pd
import numpy as np

In [4]:
###Indexing can be used to select data from tensors
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
print(T_data)

[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]]


In [5]:
x = torch.arange(1,10)
print(x)
y = x.reshape(1,3,3)
print(y)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [6]:
###indexing the middle bracket
print(y[0][0])
print(y[0][1])
print(y[0][2])
print(y[0][1][1])
print(y[0][0][1])
print(y[0][2][2])

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([7, 8, 9])
tensor(5)
tensor(2)
tensor(9)


In [7]:
###Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
print(y[:,:,1])
###Get all values of 0th and 1st dimensions but only index 2 of 2nd dimension
print(y[:,:,2])

tensor([[2, 5, 8]])
tensor([[3, 6, 9]])


In [8]:
###Get all values of 0th dimension but only 1 index value of 1st and 2nd dimension

print(y[:,1,1])

###Get index 0 of 0th and 1st dimension and all values of 2nd dimension

print(y[0,0,:])

###index on y to return [3,6,9]
print(y[:,:,2])

tensor([5])
tensor([1, 2, 3])
tensor([[3, 6, 9]])


In [14]:
###Pytorch reproducibility (trying to take random out of random)
torch.rand(3,3)


tensor([[0.5882, 0.5921, 0.8325],
        [0.2794, 0.3559, 0.0711],
        [0.3311, 0.2467, 0.5917]])

In [26]:
###Random and reproducible tensors
random_seed = 42
torch.manual_seed(random_seed)
random_tensorA = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
